### ISSUE TITLE
Concurrency model for new workflow should cancel previous execution 

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#121]
for now we use:
https://github.com/checkstyle/checkstyle/blob/6fff4fa9b16a3bb03a92de004663096815227b29/.github/workflows/diff-report.yml#L30-L33

but may be we should cancel previous executions and concurrency should be by PR number.
But it use to be line this: https://github.com/checkstyle/checkstyle/commit/22c0361c6efafbce9972ebbe005a36090d1724e6
https://github.com/checkstyle/checkstyle/pull/14069

**Comment by romani** [comment]
@relentless-pursuit  , 

I think we should cancel previous executions if one more is triggered. Please investigate how to archive this.
We already have this model in some workflows in main repo.

Example: https://github.com/checkstyle/checkstyle/blob/981c0cb87eb58cafef5c84014f94ba1f05080a46/.github/workflows/checker-framework.yml#L10-L13

**Comment by relentless-pursuit** [comment]
1. Purpose of concurrency in GitHub Actions:
   - Controls how multiple workflow runs are handled when triggered at the same time or close together.

2. Current setup:
   - Each workflow run gets a unique group (using `github.run_id`).
   - No cancellation of in-progress runs.

3. Basic options:

   a. Allow all runs (current setup):
      ```yaml
      concurrency:
        group: ${{ github.run_id }}
        cancel-in-progress: false
      ```
      - Every run executes, no matter how many are triggered.

   b. One run per PR at a time:
      ```yaml
      concurrency:
        group: ${{ github.workflow }}-${{ github.event.issue.number }}
        cancel-in-progress: false
      ```
      - Only one run per PR executes at a time.
      - New runs wait for the current one to finish.

   c. Always run latest, cancel others:
      ```yaml
      concurrency:
        group: ${{ github.workflow }}-${{ github.event.issue.number }}
        cancel-in-progress: true
      ```
      - Only the latest run for a PR executes.
      - Cancels any in-progress run when a new one is triggered.

4. Key question:
   Do you want to:
   - Run everything? (Option a)
   - Run one at a time per PR? (Option b)
   - Always run only the latest for each PR? (Option c)

The choice depends on your specific needs for the Diff-Report action. Consider factors like resource usage, how often reports are needed, and the importance of always having the very latest changes in the report.
