### ISSUE TITLE
Limit workflow to be executed on opened Pull Requests only

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#131]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request
```
on:
  pull_request:
    types:
      - opened
```

it will do extra validation that nobody starts it on non active pulls.
