### ISSUE TITLE
React with rocket is not working

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#138]
I have not see this for a while.
```  
    - uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
        name: React with rocket on run
        with:
          trigger: ','
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
```

can we use some other action ? or can we make this to work?
