### ISSUE TITLE
investigate how to void initialization of git repository for diff-java-tool

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#209]
from https://github.com/checkstyle/test-configs/pull/192#issuecomment-2395218503

investigate why can not use path to git repo by "file://"

```
.github/workflows/project.yml
projects:
  - name: diff-java-tool
    scm: git
    url: file:///home/runner/work/test-configs/test-configs/diff-java-tool
    reference: main
```
