### ISSUE TITLE
Configuration for extractor to put specific projects in specific Examp

### ISSUE THREAD

**Issue by romani** [checkstyle/test-configs#90]
We need to restore javadocsummary example with Japan period to run only on jdk and special project with Japan language javadoc comments.

**Comment by relentless-pursuit** [comment]
Can you guide me how to do this? Because for the special configs for javadocsumarry, we did manually.

**Comment by romani** [comment]
Right now we simply add config file with all projects. We do this by simple copy of file to target folder.

Instead of copy we need to create file by generation, for each  bundle if check+example is in config of extractor.

If check+example is not in config of extractor, we copy default file as we do now.

**Comment by relentless-pursuit** [comment]
> Right now we simply add config file with all projects. We do this by simple copy of file to target folder.
> 
> Instead of copy we need to create file by generation, for each bundle if check+example is in config of extractor.
> 
> If check+example is not in config of extractor, we copy default file as we do now.

Suppose, if i have a project.xml like below, i do create a project-on-properties based on this yml. is my understanding right?
```
JavadocSummary:
  Example1:
    projects:
      - project1
      - project2
  Example2:
    projects:
      - project3
      - project4
      - project5
```

> Instead of copy we need to create file by generation, for each bundle if check+example is in config of extractor.

Does this mean creating a yml configuration of extractor?
